name: "Hola mundo"

on:
  push:
    branches: ["main"]
jobs:
  deploy-githubaction-lab:
    runs-on: ubuntu-lastest
    steps:
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"
